# Generated by Django 6.0.2 on 2026-02-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_cart_id"),
        ("product", "0002_review"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem",
            unique_together={("cart", "product")},
        ),
    ]
