# Generated by Django 6.0.2 on 2026-02-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_rename_description_review_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="date",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
