# Generated by Django 6.0 on 2026-01-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_taskdetail_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="assigned_to",
            field=models.ManyToManyField(related_name="tasks", to="tasks.employee"),
        ),
    ]
