# Generated by Django 6.0 on 2026-02-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_taskasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskdetail",
            name="asset_caption",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="taskdetail",
            name="asset_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="task_assets/%Y/%m/%d/"
            ),
        ),
        migrations.DeleteModel(
            name="TaskAsset",
        ),
    ]
