# Generated by Django 6.0 on 2026-02-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0008_taskdetail_asset_caption_taskdetail_asset_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdetail",
            name="asset_image",
            field=models.ImageField(
                blank=True,
                default="task_assets/default_image.jpg",
                null=True,
                upload_to="task_assets/%Y/%m/%d/",
            ),
        ),
    ]
